version: "3"

services:
  sons-of-the-forest-server:
    image: rouhim/sons-of-the-forest-server
    build:
      context: .
      dockerfile: Containerfile
    restart: unless-stopped
    volumes:
      - "./config:/config"
      - "./data:/data"
    ports:
      - "0.0.0.0:8766:8766/udp"
      - "0.0.0.0:27016:27016/udp"
      - "0.0.0.0:9700:9700/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"